import { Router } from "express"; import multer from "multer"; import { Role } from "@prisma/client"; import { z } from "zod"; import XLSX from "xlsx"; import { prisma } from "../../config/prisma"; import { requireAuth, requireRole } from "../../middlewares/auth"; import { validate } from "../../middlewares/validate"; import { asyncHandler } from "../../utils/asyncHandler"; import { auditLog } from "../audit/audit.service";
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:4*1024*1024}}); export const productsRouter=Router(); productsRouter.use(requireAuth);
const base=z.object({sku:z.string().min(1),name:z.string().min(2),description:z.string().optional().nullable(),costPrice:z.coerce.number().min(0),salePrice:z.coerce.number().min(0),promoPercent:z.coerce.number().min(0).max(100).default(0),stock:z.coerce.number().int().min(0).default(0),minStock:z.coerce.number().int().min(0).default(0)}); const createSchema=z.object({body:base}); const updateSchema=z.object({body:base.partial()});
function margin(c:number,s:number){return s<=0?0:Number((((s-c)/s)*100).toFixed(2));} function final(s:number,p:number){return Number((s*(1-p/100)).toFixed(2));}
productsRouter.get('/',asyncHandler(async(req,res)=>{const q=String(req.query.q??''); const rows=await prisma.product.findMany({where:q?{OR:[{sku:{contains:q,mode:'insensitive'}},{name:{contains:q,mode:'insensitive'}}]}:undefined,orderBy:{createdAt:'desc'}}); res.json(rows.map(p=>({...p,costPrice:Number(p.costPrice),salePrice:Number(p.salePrice),promoPercent:Number(p.promoPercent),marginPercent:margin(Number(p.costPrice),Number(p.salePrice)),finalPrice:final(Number(p.salePrice),Number(p.promoPercent))})));}));
productsRouter.post('/',requireRole(Role.ADMIN),validate(createSchema),asyncHandler(async(req,res)=>{const product=await prisma.product.create({data:req.body}); await auditLog({userId:req.user?.id,action:'CREATE',tableName:'Product',recordId:product.id,newData:product,ipAddress:req.ip}); res.status(201).json(product);}));
productsRouter.patch('/:id',requireRole(Role.ADMIN),validate(updateSchema),asyncHandler(async(req,res)=>{const oldData=await prisma.product.findUniqueOrThrow({where:{id:req.params.id}}); const product=await prisma.product.update({where:{id:req.params.id},data:req.body}); await auditLog({userId:req.user?.id,action:'UPDATE',tableName:'Product',recordId:product.id,oldData,newData:product,ipAddress:req.ip}); res.json(product);}));
productsRouter.patch('/:id/toggle',requireRole(Role.ADMIN),asyncHandler(async(req,res)=>{const oldData=await prisma.product.findUniqueOrThrow({where:{id:req.params.id}}); const product=await prisma.product.update({where:{id:req.params.id},data:{isActive:!oldData.isActive}}); await auditLog({userId:req.user?.id,action:'TOGGLE_ACTIVE',tableName:'Product',recordId:product.id,oldData,newData:product,ipAddress:req.ip}); res.json(product);}));
productsRouter.get('/template/excel',requireRole(Role.ADMIN),(_req,res)=>{const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{sku:'SKU-001',name:'Producto ejemplo',description:'Descripción opcional',costPrice:50,salePrice:100,promoPercent:0,stock:10,minStock:2}]),'productos'); res.setHeader('Content-Disposition','attachment; filename=formato-productos.xlsx'); res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); res.send(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}));});
productsRouter.post('/import/excel',requireRole(Role.ADMIN),upload.single('file'),asyncHandler(async(req,res)=>{ if(!req.file) return res.status(400).json({message:'Archivo requerido'}); const wb=XLSX.read(req.file.buffer); const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]]); let count=0; for(const r of rows){ const sku=String(r.sku??'').trim(); const name=String(r.name??'').trim(); if(!sku||!name) continue; await prisma.product.upsert({where:{sku},update:{name,description:r.description?String(r.description):undefined,costPrice:Number(r.costPrice??0),salePrice:Number(r.salePrice??0),promoPercent:Number(r.promoPercent??0),stock:Number(r.stock??0),minStock:Number(r.minStock??0),isActive:true},create:{sku,name,description:r.description?String(r.description):undefined,costPrice:Number(r.costPrice??0),salePrice:Number(r.salePrice??0),promoPercent:Number(r.promoPercent??0),stock:Number(r.stock??0),minStock:Number(r.minStock??0)}}); count++; } await auditLog({userId:req.user?.id,action:'IMPORT_EXCEL',tableName:'Product',newData:{count},ipAddress:req.ip}); res.json({imported:count});}));
